# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeschoolApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='What is your first name?')),
                ('last_name', models.CharField(max_length=100, verbose_name='What is your family (last) name?')),
                ('email', models.CharField(max_length=100, verbose_name='What is your email?')),
                ('street_address', models.CharField(blank=True, max_length=200, verbose_name='What is your street address?')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='What is your city?')),
                ('state', models.CharField(blank=True, default='CA', max_length=2, verbose_name='What state do you live in?')),
                ('zipcode', models.CharField(blank=True, max_length=10, verbose_name='What is your zip code?')),
                ('phone_cell', models.CharField(blank=True, max_length=20, verbose_name='What is your cell phone number?')),
                ('phone_land', models.CharField(blank=True, max_length=20, verbose_name='What is your home telephone number?')),
                ('occupation', models.CharField(blank=True, max_length=50, verbose_name='What is your occupation?')),
                ('hh_income', models.CharField(blank=True, max_length=50, verbose_name='What is your household income?')),
                ('own_cats', models.CharField(blank=True, max_length=50, verbose_name='Do you own cats?')),
                ('other_pets', models.CharField(blank=True, max_length=50, verbose_name='Do you have any other pets?')),
                ('date_found', models.DateField(blank=True, verbose_name='When did you find the kitten(s)?')),
                ('num_found', models.CharField(blank=True, max_length=50, verbose_name='How many kitten(s) were found?')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Where you find the kitten(s). Was it a business/home/school/field/or ...')),
                ('seen_mom', models.CharField(blank=True, max_length=50, verbose_name='Have you seen the mom-cat?')),
                ('seen_other_strays', models.CharField(blank=True, max_length=50, verbose_name='Have you seen other strays?')),
                ('notes_public', models.TextField(blank=True, verbose_name='Is there any additional information which would helpful?')),
                ('notes_private', models.TextField(blank=True, verbose_name='Private KB Notes about location.')),
            ],
        ),
    ]
