# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeschoolapplication',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
