# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0002_homeschoolapplication_application_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('A', 'Adopted'), ('D', 'Deceased'), ('I', 'Intake'), ('R', 'Released'), ('O', 'Other')], max_length=1)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('birthdate', models.DateField(blank=True)),
                ('first_assessment', models.DateField(blank=True)),
                ('first_assessment_weight', models.CharField(blank=True, max_length=20)),
                ('second_assessment', models.DateField(blank=True)),
                ('second_assessment_weight', models.CharField(blank=True, max_length=20)),
                ('FVRCP_01', models.DateField(blank=True)),
                ('FVRCP_01_note', models.CharField(blank=True, max_length=20)),
                ('FVRCP_02', models.DateField(blank=True)),
                ('FVRCP_02_note', models.CharField(blank=True, max_length=20)),
                ('deworm_01', models.DateField(blank=True)),
                ('deworm_01_note', models.CharField(blank=True, max_length=20)),
                ('deworm_02', models.DateField(blank=True)),
                ('deworm_02_note', models.CharField(blank=True, max_length=20)),
                ('flea_01', models.DateField(blank=True)),
                ('flea_01_note', models.CharField(blank=True, max_length=20)),
                ('flea_02', models.DateField(blank=True)),
                ('flea_02_note', models.CharField(blank=True, max_length=20)),
                ('sneuter', models.DateField(blank=True)),
                ('sneuter_location', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='hh_income',
            field=models.CharField(choices=[('24', '24,000 or Below'), ('35', 'Between 24,000 and 35,000'), ('65', 'Between 35,000 and 65,000'), ('99', 'Above 65,000')], max_length=2, verbose_name='What is your household income?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='notes_private',
            field=models.TextField(blank=True, verbose_name='Private KB Notes.'),
        ),
    ]
