# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0004_auto_20171122_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeschoolapplication',
            name='rescue_type',
            field=models.CharField(blank=True, choices=[('IR', 'Indie Rescuer'), ('HS', 'Homeschool'), ('GC', 'Guidence Counselor'), ('FS', 'Foster')], max_length=2),
        ),
    ]
