# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0006_auto_20171122_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitten',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hs.HomeschoolApplication'),
        ),
    ]
