# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0007_kitten_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='What is your city?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='date_found',
            field=models.DateField(blank=True, null=True, verbose_name='When did you find the kitten(s)?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='hh_income',
            field=models.CharField(blank=True, choices=[('24', '24,000 or Below'), ('35', 'Between 24,000 and 35,000'), ('65', 'Between 35,000 and 65,000'), ('99', 'Above 65,000')], max_length=2, null=True, verbose_name='What is your household income?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Where you find the kitten(s). Was it a business/home/school/field/or ...'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='notes_private',
            field=models.TextField(blank=True, null=True, verbose_name='Private KB Notes.'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='notes_public',
            field=models.TextField(blank=True, null=True, verbose_name='Is there any additional information which would helpful?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='num_found',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='How many kitten(s) were found?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='What is your occupation?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='other_pets',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Do you have any other pets?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='own_cats',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Do you own cats?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='phone_cell',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='What is your cell phone number?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='phone_land',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='What is your home telephone number?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='rescue_type',
            field=models.CharField(blank=True, choices=[('IR', 'Indie Rescuer'), ('HS', 'Homeschool'), ('GC', 'Guidence Counselor'), ('FS', 'Foster')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='seen_mom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Have you seen the mom-cat?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='seen_other_strays',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Have you seen other strays?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='state',
            field=models.CharField(blank=True, default='CA', max_length=2, null=True, verbose_name='What state do you live in?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What is your street address?'),
        ),
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='What is your zip code?'),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='FVRCP_01',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='FVRCP_01_note',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='FVRCP_02',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='FVRCP_02_note',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='deworm_01',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='deworm_01_note',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='deworm_02',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='deworm_02_note',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='first_assessment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='first_assessment_weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='flea_01',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='flea_01_note',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='flea_02',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='flea_02_note',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='outcome',
            field=models.CharField(blank=True, choices=[('A', 'Adopted'), ('D', 'Deceased'), ('I', 'Intake'), ('R', 'Released'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='second_assessment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='second_assessment_weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='sneuter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='sneuter_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
