# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0009_auto_20171123_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='hh_income',
            field=models.CharField(blank=True, choices=[('24', 'Below 24,000'), ('35', 'Between 24,000 and 35,000'), ('65', 'Between 35,000 and 65,000'), ('99', 'Above 65,000')], max_length=2, null=True, verbose_name='What is your household income?'),
        ),
    ]
