# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0010_auto_20171124_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeschoolapplication',
            name='application_status',
            field=models.CharField(choices=[('A', 'Active'), ('O', 'Open'), ('C', 'Closed'), ('P', 'Pending'), ('N', 'New Contact')], default='N', max_length=1),
        ),
    ]
