# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0013_auto_20171125_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeschoolapplication',
            name='est_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='What is the estimated age of the kittens found?'),
        ),
        migrations.AddField(
            model_name='kitten',
            name='is_ready_for_adoption',
            field=models.BooleanField(default=False),
        ),
    ]
