# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0013_auto_20171125_2028'),
        ('hs', '0010_auto_20171123_2315'),
    ]

    operations = [
    ]
