# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0014_auto_20171201_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeschoolapplication',
            name='notes_public',
            field=models.TextField(blank=True, null=True, verbose_name='Is there any additional information which would helpful? Please describe the kittens.'),
        ),
    ]
