# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0015_auto_20171201_2006'),
        ('hs', '0014_merge_20171125_2250'),
    ]

    operations = [
    ]
