# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0019_kitten_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeschoolapplication',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='outcome',
            field=models.CharField(blank=True, choices=[('P', 'In HS Program'), ('A', 'Adopted'), ('D', 'Deceased'), ('E', 'Escaped'), ('F', 'Homeschool Fail Adoption'), ('I', 'Intake'), ('R', 'Released'), ('T', 'TIAA'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='source',
            field=models.CharField(blank=True, choices=[('P', 'Public'), ('K', 'Kitty Cadet'), ('T', 'TNR'), ('V', 'Volunteer'), ('U', 'Unknown')], default='U', max_length=1, null=True),
        ),
    ]
